package View;



import Controller.Algorithm;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Oshin
 */
public class how extends javax.swing.JFrame {

    Highlighter.HighlightPainter myHighlightPainter = new MyHighLighterPainter(Color.red);

    Algorithm summary = new Algorithm();

    public how() {
        initComponents();

    }

   

    class MyHighLighterPainter extends DefaultHighlighter.DefaultHighlightPainter {

        public MyHighLighterPainter(Color color) {
            super(color);
        }
    }

    public void highlight(JTextComponent txtAreaOutputDocument, String pattern) {

        try {

            Highlighter hilite = txtAreaOutputDocument.getHighlighter();
            Document doc = txtAreaOutputDocument.getDocument();
            String text = doc.getText(0, doc.getLength());
            int pos = 0;//position

            while ((pos = text.toUpperCase().indexOf(pattern.toUpperCase(), pos)) >= 0) {
                hilite.addHighlight(pos, pos + pattern.length(), myHighlightPainter);
                pos += pattern.length();
            }

        } catch (Exception e) {
        }

    }

//    public void writeOriginalDocumentToFile() {
//        try {
//            FileOutputStream out = new FileOutputStream(new File("originalText.txt"));
//            out.write(txtAreaInputDocument.getText());
//        } catch (FileNotFoundException e) {
//            System.out.println(e);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGrpGender = new javax.swing.ButtonGroup();
        jTabbedPaneHead = new javax.swing.JTabbedPane();
        jTabbedPaneSub = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaOutputDocument = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblCompressionRatio = new javax.swing.JLabel();
        lblNoOfParagraphsInContext = new javax.swing.JLabel();
        lblNoOfParagraphsInSummary = new javax.swing.JLabel();
        lblNoOfWordsSummary = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblNoOfWordsInContext1 = new javax.swing.JLabel();
        lblNoOfSentencesInContext = new javax.swing.JLabel();
        jPanelExit = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(32, 33, 35));
        setUndecorated(true);
        setResizable(false);

        jTabbedPaneHead.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTabbedPaneHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneHeadMouseClicked(evt);
            }
        });

        jTabbedPaneSub.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaOutputDocument.setEditable(false);
        txtAreaOutputDocument.setColumns(20);
        txtAreaOutputDocument.setRows(5);
        jScrollPane2.setViewportView(txtAreaOutputDocument);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 930, 280));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Commpression Ratio :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 160, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Number of words in Context(Input Document) :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 340, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Number of  Sentences in Context :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 250, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Number of words in Summary(Output) :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 290, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Number of  Paragraphs in Summary :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 260, -1));

        lblCompressionRatio.setForeground(new java.awt.Color(204, 0, 0));
        lblCompressionRatio.setText("..");
        jPanel1.add(lblCompressionRatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 170, -1));

        lblNoOfParagraphsInContext.setForeground(new java.awt.Color(204, 0, 0));
        lblNoOfParagraphsInContext.setText("..");
        jPanel1.add(lblNoOfParagraphsInContext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 90, -1));

        lblNoOfParagraphsInSummary.setForeground(new java.awt.Color(204, 0, 0));
        lblNoOfParagraphsInSummary.setText("..");
        jPanel1.add(lblNoOfParagraphsInSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 120, -1));

        lblNoOfWordsSummary.setForeground(new java.awt.Color(204, 0, 0));
        lblNoOfWordsSummary.setText("..");
        jPanel1.add(lblNoOfWordsSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 120, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Number of  Paragraphs in Context :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 260, -1));

        lblNoOfWordsInContext1.setForeground(new java.awt.Color(204, 0, 0));
        lblNoOfWordsInContext1.setText("..");
        jPanel1.add(lblNoOfWordsInContext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 110, -1));

        lblNoOfSentencesInContext.setForeground(new java.awt.Color(204, 0, 0));
        lblNoOfSentencesInContext.setText("..");
        jPanel1.add(lblNoOfSentencesInContext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 120, -1));

        jTabbedPaneSub.addTab("                                                                    Detailed Description                                                    ", jPanel1);

        jTabbedPaneHead.addTab("                                            Intelligent Text Summarizer                                      ", jTabbedPaneSub);

        jPanelExit.setBackground(new java.awt.Color(32, 33, 35));
        jPanelExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneHead.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png")), jPanelExit); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneHead)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneHead)
        );

        jTabbedPaneHead.getAccessibleContext().setAccessibleName("     Me     ");

        setSize(new java.awt.Dimension(976, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneHeadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneHeadMouseClicked
     
    }//GEN-LAST:event_jTabbedPaneHeadMouseClicked

    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(how.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(how.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(how.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(how.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new how().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneHead;
    private javax.swing.JTabbedPane jTabbedPaneSub;
    private javax.swing.JLabel lblCompressionRatio;
    private javax.swing.JLabel lblNoOfParagraphsInContext;
    private javax.swing.JLabel lblNoOfParagraphsInSummary;
    private javax.swing.JLabel lblNoOfSentencesInContext;
    private javax.swing.JLabel lblNoOfWordsInContext1;
    private javax.swing.JLabel lblNoOfWordsSummary;
    private javax.swing.ButtonGroup radGrpGender;
    private javax.swing.JTextArea txtAreaOutputDocument;
    // End of variables declaration//GEN-END:variables

}
